src/Entity/AccountValidation.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AccountValidationRepository")
 */
class AccountValidation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", cascade={"persist"},fetch="EAGER")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $token;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(string $token): self
    {
        $this->token = $token;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}
        	<link rel="stylesheet" type="text/css" href="{{asset('css/style.css')}}">
        {% endblock %}
        <script
          src="https://code.jquery.com/jquery-3.3.1.min.js"
          integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
          crossorigin="anonymous"></script>
          <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    </head>
    <body>
        <section id="notif">
            <ul id="notif-list">
                
            </ul>
        </section>

        {% include 'header.html.twig' %}

        {% block body %}{% endblock %}

        {% block javascripts %}{% endblock %}

        <script src="{{asset('js/general.js')}}"></script>
        <script>
            $(document).ready(function() {
                {% for message in app.flashes('notification') %}
                    var notif = JSON.parse("{{message|escape('js')}}");
                    createNotif(notif);

                {% endfor %}
            });
        </script>
    </body>
</html>

templates/header.html.twig
<header id="menu">
	<img src="{{asset('images/snow.jpg')}}"  />
	<ul >
		<li><a href="/">Home</a></li>
		<li><a href="/trick/add">Trick</a></li>
		
		{% if not app.user %}
    		<li><a href="/login">sign in</a></li>
			<li><a href="/register">sign up</a></li>
		{% else %}
			<li><a href="/profile">profile</a></li>
			<li><a href="/logout">logout</a></li>
		{% endif %}
		
	</ul>
	
</header>


<button id="phone-trigger-menu"><i class="fas fa-align-justify"></i></button>
<header id="phone-menu">

	<ul>
		<li><a href="/">Home</a></li>
		<li><a href="/trick/add">Trick</a></li>
		
		{% if not app.user %}
    		<li><a href="/login">sign in</a></li>
			<li><a href="/register">sign up</a></li>
		{% else %}
			<li><a href="/profile">profile</a></li>
			<li><a href="/logout">logout</a></li>
		{% endif %}
		
	</ul>
</header>

templates/home.html.twig
{% extends 'base.html.twig' %}
{% block body %}
	<section id="home-header">
			<h1>The reference of snowboard tricks</h1>
	</section>

	<section id="trick-list">
		<ul>

		</ul>
		<button id="load-more">load more</button>
	</section>

	<script>
		{% if not app.user %}
    		var connected = false;
		{% else %}
			var connected = true;
		{% endif %}

		var page = 1;
		loadTrick(page);
	    function loadTrick(pagination){
	    	$.ajax({
				url : 'http://{{app.request.httpHost}}/api/trick/' + pagination + '',
				type : 'GET',
				dataType : 'json',
				success : function(objList, statut){
					objList = JSON.parse(objList);
					var i = 0;

					while(i < objList.length){
						var link = $('<a>',{href:"/trick/view/" + objList[i].id +"",})
						var image = $("<img>",{src:"/uploads/trick/" + objList[i].imageList[0].name + "",})
						var title = $('<h2>',{text:objList[i].name});
						var li = $('<li>');
						var btnEdit = $('<div>',{html:"<i class='fas fa-edit'></i>","data-id":objList[i].id,class:"trick-edit"});
						var btnDelete = $('<div>',{html:"<i class='fas fa-trash-alt'></i>","data-id":objList[i].id,class:"trick-delete"});
						image.appendTo(link);
						title.appendTo(link);
						link.appendTo(li);
						if(connected){
							btnEdit.appendTo(li);
							btnDelete.appendTo(li);
						}
						$("#trick-list ul").append(li);
						i++;
					}
					$(".trick-edit").click(function(){
						var id = $(this).data('id');
						window.location.replace("/trick/edit/" + id + "");
					});

					$(".trick-delete").click(function(){
						var id = $(this).data('id');
						var r = confirm("are you sure to delete this trick ?");
						if (r == true) {
						  window.location.replace("/trick/remove/" + id + "");
						}

					});
					page++;

					if(objList.length == 0){
						page--;
						$("#load-more").hide();
					}
				},

				error : function(resultat, statut, erreur){

				}

	    	});
	    }

	    $( "#load-more" ).click(function() {
			loadTrick(page);
		});

	</script>
{% endblock %}

templates/trick.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{trick.getName()}}{% endblock %}

{% block body %}
	<div id="trick-content">
		<section id="trick-header">
			{% if app.user %}
    			<div id="btn-edit"><a href="/trick/edit/{{trick.id}}"><i class='fas fa-edit'></i></a></div>
			{% endif %}
			
			<img id="trick-img-header" src="{{asset('uploads/trick/'~ trick.imageList[0].name ~'')}}" />
			<h1 id="trick-header-title">{{trick.getName()}} </h1>
		</section>
		<section id="trick-media">
			{% for video in trick.getVideoList() %}
	        	<embed type="video/webm" src="{{video}}"/>
	    	{% endfor %}


			{% for image in trick.getImageList() %}
	        	<img src="{{asset('uploads/trick/'~ image.getName() ~'')}}" />
	    	{% endfor %}
	    </section>

		<p id="trick-description">{{trick.getDescription()}}</p>

		<section id="trick-additionalInfo">
	    	<ul>
	    		<li class="trick-group">{{trick.getCategory().getName()}}</li>
	    		<li class="trick-date">created at {{trick.getCreatedAt()|date('Y-m-d h:m')}}</li>
	    		{% if trick.getEdited == 'yes' %}
    				<li class="trick-date">Edited at {{trick.getEditedAt()|date('Y-m-d h:m')}}</li>
				{% endif %}
	    	</ul>
	    </section>

	    {% if app.user %}
			{{ form_start(form) }}		
			{{ form_end(form) }}
		{% endif %}

	    <ul id="comment-list">
	       
	    </ul>
	    <button id="load-more">load more</button>

	</div>
	<script type="text/javascript">
		var page = 1;
		loadComments(page);
	    function loadComments(pagination){
	    	$.ajax({
				url : 'http://{{app.request.httpHost}}/api/message/{{trick.id}}/' + pagination +'',
				type : 'GET',
				dataType : 'json',
				success : function(objList, statut){
					objList = JSON.parse(objList);
					var i = 0;
					
					while(i < objList.length){
						if(objList[i].author.avatar == "default.png"){
							var avatar = "/images/defaultAvatar.png"
						}
						else{
							var avatar = "/uploads/avatar/" + objList[i].author.avatar;
						}
						$("#comment-list").append("<li class='clearfix'><div id='comment-user-info'> <img src='" + avatar + "' /><p class='comment-username'>" + objList[i].author.username + "</p></div><div id='comment-content'> <p id='comment-text'>" + objList[i].content + "</p></div> </li>");

						i++;
					}
					page++;
					
					if(objList.length == 0){
						page--;
						$("#load-more").hide();
					}
				},

				error : function(resultat, statut, erreur){

				}
	    	});
	    }

		$( "#load-more" ).click(function() {
			loadComments(page);
		});
	</script>
{% endblock %}